### ISSUE TITLE
git submodule update fails

### ISSUE THREAD

**Issue by parjong** [Microsoft/checkedc-llvm#1]
Running `git submodule update` shows the following prompt:

```
$ git submodule update
Cloning into 'projects/checkedc-wrapper/checkedc'...
Username for 'https://msresearch.visualstudio.com':
```

Should I change `tools/clang` to refer to `https://github.com/Microsoft/checkedc-clang.git`?

**Comment by dtarditi** [comment]
Thanks for pointing this out.  I’ll update the submodule links after I commit the current pull requests for this repo and the checkedc repo.  First those pull requests need to go through code review.
